// 将独立场景插画与代码绘制的像素标题、光点合成浏览器动画，再编码成 GIF。
// 原始插画不改写；只输出展示文件，不访问任何远程发布接口。
const fs = require('node:fs');
const path = require('node:path');
const {pathToFileURL} = require('node:url');
const deps = process.argv[2];
if (!deps) throw new Error('请传入已安装 playwright 和 sharp 的 node_modules 目录');
const {chromium} = require(require.resolve('playwright', {paths:[deps]}));
const sharp = require(require.resolve('sharp', {paths:[deps]}));
const root = path.resolve(__dirname, '..');
const assets = path.join(root, '仓库首页/展示资源');
// 角标版本号取自 gradle.properties，避免版本升级后封面还停在上一个测试版。
const modVersion = /^mod_version=(.+)$/m.exec(fs.readFileSync(path.join(root, '..', 'gradle.properties'), 'utf8'))[1].trim();
// 标题使用自绘点阵字形，无字体下载或游戏字体依赖。
const glyphs = {y:['10001','10001','01010','00100','00100','00100','00100'],i:['111','010','010','010','010','010','111'],a:['01110','10001','10001','11111','10001','10001','10001'],d:['11110','10001','10001','10001','10001','10001','11110'],o:['01110','10001','10001','10001','10001','10001','01110'],n:['10001','11001','11001','10101','10011','10011','10001']};
let x=0, shapes='';
for(const letter of 'yiyiaddon') {const glyph=glyphs[letter];glyph.forEach((row,j)=>[...row].forEach((v,i)=>{if(v==='1')shapes+=`<rect x="${x+i*9}" y="${j*9}" width="9" height="9"/>`}));x+=(glyph[0].length+1)*9;}
const logo=`<svg viewBox="0 0 ${x} 70" width="${x}" height="70" aria-label="yiyiaddon"><g fill="#f7f2da">${shapes}</g></svg>`;
const sparks=Array.from({length:16},(_,i)=>`<i class="spark" data-index="${i}" style="left:${9+(i*19)%83}%;top:${20+(i*13)%52}%"></i>`).join('');
const imageUrl='data:image/png;base64,'+fs.readFileSync(path.join(assets,'方块世界场景.png')).toString('base64');
const html=`<!doctype html><html><head><meta charset="utf-8"><style>
*{box-sizing:border-box}body{margin:0;background:#161b13;font-family:'Microsoft YaHei',sans-serif}.cover{width:1120px;height:520px;position:relative;overflow:hidden;border:3px solid #444837;background:#172316}.scene{position:absolute;inset:0;width:100%;height:100%;object-fit:cover}.shade{position:absolute;inset:0;background:linear-gradient(0deg,rgba(13,20,13,.98),rgba(13,20,13,.55) 35%,transparent 70%)}.topline{position:absolute;left:32px;right:32px;top:25px;display:flex;justify-content:space-between;font-size:12px;color:#f5ecd0;text-shadow:1px 2px #232718;letter-spacing:1px}.status{padding:7px 11px;background:#1e2a1dcf;border:1px solid #a1ab69;box-shadow:inset 2px 2px #c2c88520}.wordmark{position:absolute;left:37px;bottom:99px;filter:drop-shadow(4px 5px 0 #161e14)}.caption{position:absolute;left:38px;bottom:71px;color:#d3d4b6;font-size:16px;letter-spacing:3px}.bottom{position:absolute;bottom:0;left:0;right:0;height:49px;display:flex;align-items:center;border-top:1px solid #73805160;background:#151c13}.bottom span{padding:0 28px;color:#c6ccae;font-size:12px;border-right:1px solid #525e3e}.bottom .hint{margin-left:auto;border:0;font-size:11px;color:#98a287}.spark{position:absolute;width:3px;height:3px;background:#fbd585;box-shadow:0 0 7px #f8ca7b}.shine{position:absolute;left:84%;top:49%;width:12px;height:12px;background:#74bfc26b;filter:blur(5px)}.cloud{position:absolute;top:5%;left:13%;width:145px;height:20px;background:#ffe5bc0b;box-shadow:40px 14px #ffe5bc07,85px -9px #ffe5bc06}
</style></head><body><div class="cover"><img class="scene" src="${imageUrl}"><div class="cloud"></div><div class="shine"></div>${sparks}<div class="shade"></div><div class="topline"><span>独立 FABRIC 客户端模组</span><span class="status">${modVersion} · 公开测试版</span></div><div class="wordmark">${logo}</div><div class="caption">星露谷农场 / 自动挖矿 / 物品与后勤</div><div class="bottom"><span>MINECRAFT 26.x</span><span>FABRIC</span><span>JAVA 25</span><span class="hint">方块场景概念插画 · 非实机画面</span></div></div><script>window.frame=t=>{document.querySelectorAll('.spark').forEach((p,i)=>{const a=t*Math.PI*2+i*.73;p.style.transform='translate('+Math.sin(a)*9+'px,'+Math.cos(a)*12+'px)';p.style.opacity=.2+.35*(1+Math.sin(a))});document.querySelector('.cloud').style.transform='translateX('+Math.sin(t*Math.PI*2)*18+'px)';document.querySelector('.shine').style.opacity=.35+.3*Math.sin(t*Math.PI*2)}</script></body></html>`;
(async()=>{const browser=await chromium.launch({channel:'msedge',headless:true});try{const page=await browser.newPage({viewport:{width:1120,height:520},deviceScaleFactor:1});await page.setContent(html);await page.locator('.scene').evaluate(img=>img.decode());const frames=[];for(let i=0;i<40;i++){await page.evaluate(t=>window.frame(t),i/40);frames.push(await page.screenshot());}fs.writeFileSync(path.join(assets,'方块世界封面.png'),frames[0]);await sharp(frames,{join:{animated:true}}).gif({delay:125,loop:0,colours:192,dither:.2,interFrameMaxError:8,effort:7}).toFile(path.join(assets,'方块世界封面.gif'));const meta=await sharp(path.join(assets,'方块世界封面.gif'),{animated:true}).metadata();console.log(JSON.stringify({width:meta.width,pageHeight:meta.pageHeight,pages:meta.pages,bytes:fs.statSync(path.join(assets,'方块世界封面.gif')).size}));}finally{await browser.close()}})().catch(e=>{console.error(e);process.exit(1)});
