package com.yiyiaddon.e.d.b;

public enum c {
   IDLE,
   OPEN_LOGIN_MENU,
   CLICK_LOGIN_SURVIVAL,
   WAIT_WELCOME,
   SCAN_WELCOME,
   WAIT_MAIN_CITY,
   OPEN_AFK_MENU,
   CLICK_RETURN_MAIN_CITY_HALL,
   WAIT_MAIN_CITY_HALL,
   OPEN_MAIN_CITY_HALL_MENU,
   OPEN_CITY_MENU,
   CLICK_WORLD_TRANSFER,
   CLICK_SURVIVAL_FIRST,
   CLICK_SURVIVAL_SECOND,
   CLICK_TARGET_SERVER,
   WAIT_TARGET,
   COMPLETE,
   FAILED;
}
